### ISSUE TITLE
What would it take to bundle ffprobe? 

### ISSUE THREAD

**Issue by TableMountain** [asticode/go-astivid#5]
I'm just familiarizing myself with go-astilectron, sorry if this is an easy question. Thanks for doing this project! I'm looking forward to using it and contributing.

**Comment by asticode** [comment]
@TableMountain There are 2 difficulties regarding ffmpeg and ffprobe in this project:

1) We have to make sure it's present in the execution environment
2) We have to make sure our app point to the right path

Your question is clearly 1) but 2) shouldn't be ignored in this case.

Now back to your question. There are 2 options:

- either we bundle it outside of go-astilectron. Which means the binaries are not embedded in your final GO binary and we simply add a download step before running the bootstrap that will download the proper binary based on the OS/arch couple and place it where it should be.
- either we find a way to adapt the bundler so that this step is part of its process and the binaries are embedded based on the OS/arch couple

Does that make sense?
