### ISSUE TITLE
Dosn‘t work on windows？

### ISSUE THREAD

**Issue by gobigdev** [asticode/go-astivid#6]
![image](https://user-images.githubusercontent.com/32873792/41135545-aef9d294-6b04-11e8-8e28-9f1f590a6f77.png)

**Comment by asticode** [comment]
@yhcd you have to update the configuration for that ([here](https://github.com/asticode/go-astivid/blob/master/configuration.go#L34) and [here](https://github.com/asticode/go-astivid/blob/master/configuration.go#L31)). Otherwise it will try to use `ffmpeg` in `/usr/local/bin/ffmpeg` and `ffprobe` in `/usr/local/bin/ffprobe`.

Does that fix your issue?
